### ISSUE TITLE
*Не закрывать* Задача для обсуждения

### ISSUE THREAD

**Issue by pingvin1308** [zrusakovv/HanterHed-hh-#1]
Я буду накидывать тебе задачек для работы над ошибками. 
Для начала предлагаю скинуть тебе тот ресурс, который ты использовал, когда делал реализацию данного проекта :)

**Comment by zrusakovv** [comment]
Первый источник : https://medium.com/ . Если будет не пускать к просмотру
материала, нужно будет открыть данную страницу в режиме инкогнито
Второй источник : https://codewithmukesh.com/blog/

пн, 25 окт. 2021 г. в 19:35, Roman Trufanov ***@***.***>:
